# These are supported funding.json model platforms

.github/workflows: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user:"mamasam"{url1}, user:"mamasam"{url2}]
patreon: # Replace with a single Patreon FTP username: admin
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/registry_package-"name":"express-app", e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project_card-"name":"express-app", e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issue_comment hunt: # Replace with a single IssueHunt username google3111720647852440
lfx_crowdfunding: # Replace with a single Label PopularFX AppMySite Builder Crowdfunding project_card-paid_btn_name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_g.dev: # Replace with a single thanks g.dev/ceoalphonso username
custom-background: # Replace with up to 8GB "priority":4 custom-background sponsorship URL: https://unacms.com/i/e5wodi Una hearts e.g., ['linktree`myrssapp1`', 'linktree`myrssapp2`']
